language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  sonarcloud:
    organization: fs23-ase
    token:
      secure: "YE4enDl9Bi5HOX/Z+inBKFwBpf09OXxV1bU4uOSYt01vmJqG+ZHbWR5Osq9X+LzAxz6albrS2F3gqwqRaf9vNyWRO3QjkGWAjJuDqnDVO1+vLmqC8GhF/5kaWHBlkZ76GAs6fcYzPGL1ah7Bxhr9VFdt8fx1Z8C2iZNCuXZclUZ5/MH+vx3oc2/MTlTQWtW0rQXrsNZ9UACE+aso4rb3blKjBlwxdYU0sqElXaUarz/Q00JBhRCZFOdFygCcQc6f7Cdy6RLgj5CxzkawdCnLChXaRKShmBZnpeBKwnymhq/eStTAItyg2GsGumlY+nhC13sSczPVBFpXBtFFFEfy0RRsilvGYJiQIACu9PTYawSSsIBoPdzF/CK4A2wQjuUo8qqd5beeQafEkopC7FRWjx1ein0CNlk/47VMZTxKS3ye+/ZYoudCDj5L64Hyanxxcuk2EEQ4/r9HV82XmMINEVigamv5tWlC2m/2yBQa959iR+cOWabQ/laKp3Ihz2o+gxmA5o3DPsK4noxxU6L7sMfk84OSL16SGWAXwaM21xLM2lNtrCOhYiDmluAmlWIroTb0GC7jmlKS7HGuf1yGhn1q9FahpGqds+HA4y2WTGSUTCMkzVILzaQe0ScTwPzgsrwioSxpA38J79e2AQ2AGIcb+auoHpW+I5ILjgtdoyY="
script:
- "./gradlew sonar --info"
