language: java

addons:
  sonarcloud:
    organization: fs23-ase
    token:
      secure: "nlKJ0B8zx2+RTnh8w8F6VifHtR2mdg2b8/0w7iMj0pS6GIws5ircyda+w2oxocGJ6PcDXzdjMKky0ZouMEI8+nGn5ZlI20hnrps4V678Yz1W1g4VmaY0LjfGmE5r+xyqbp22mVTOCnAgbAV1vcxhp7KUAosJlfJI4Kq36OP4mm/hfX8t5RaphhAhjKWVJRQqoa3EGhuu+7vHBgrsAg0plEcgxrsbZJBUF6++Qyszu15VMw+v9CJiDJcJXr4YQlACkmMe/Czr0qy4ZurNbXj9HthI5XSgAvNZ61vmxuqRsYP6Gym7qrlUIuyGoKPz5Ssg4BmcqcBkiQEP6LAjvHQuohvqeqtQCEqfvGBsjCF7fI38wHYXjg6RMH1xpKDxID3zhnszTE0bQpc23fPNm0uRdYuiPAEh1lzvvrPsZL0JzFE8cKI+DTgo7J4kZeZo7C7rIeCujZgU4RQtxhC9LZJ+LsJHmDFar61kaaP7O3AWH2vSbPLcMXiehU2YyT6Ob6fOMOf+7tIOachFHL2FySqrPx9VSVXLPYOZcFFfLgUTbgiYN+FHC/XVmsTMdJ40mLx2tzIzLQs4n0nGcwewhg6auBC0AbukC5fiaIS3+bISx95IBFYlrmg65BL0pbRUbWVkaf7SUpAJbJ0Xa8chCMim6PZtTAmUvMTSWBeZoOqICTg="
script:
  - ./gradlew sonar --info
