language: java

addons:
  sonarcloud:
    organization: fs23-ase
    token:
      secure: "qA/5Dkp0KXWHCCypKZRMFuMaJDV7sXqHngXSKHoenlOc9IWD4xM2xUo3yj+PV3cXTJKy5SAWUxKJnhJlIM5aQfgQOz6VunZxydv06h4VMBKCHBsXY+ZesaTGCXLDa2nprGXc9LR7p1UibNlCB9Cj3pg9r5LQDlfEyjGZW2b5utKjCk2NdFwN6g3JuD87K0FTZUx2T25HuxracZsVZG51IDosbQoz6kuLUwtaPffZ16cUApwnqZuFiSaJK+SR8+mdKcd+P6J7BgcMkPNIBX8hGWhxr8PoiyzkqkBb7pznIK1vXKPESLVmLJYRPwcEUEgqDqMDRwQjp9O36grxl6YvSw1bGdhtc+JJrfb94mLlsv3LzATcHcwrFOKUQNNjSloyijLA8R4IXYP3iI4kceia8lo78sq9/zo5QcZ4BY398WTSt8kRgc1hieK6SkbXLsUB3ODDfhRTbviZlKlj9BlnJwGlTbmRx/TCz8YMvdGgeDYJh/DhjP/5CAQqP650QnTrA3Ma9GRGqqhG9AfhMMNOyXGKIGBxSMlYOQy/veT5MDZfzcl7whhBWxCBmfJpIuAZ3kW2lJsEgwq0Nuk2tNJ66DpPOZm9tzXwVP6nRpkwFPeNu92J3WzDkuFSfwlLXpME5W5P2/eCPA9xJsk0te/00YtsxJViqPk1EaZ4m/LZl/0="
script:
  - ./gradlew sonar --info
