name: Deploy Project to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade --user awscli

      - name: Install Elastic Beanstalk CLI
        run: |
          mkdir -p ~/.ebcli-app
          export PATH=$PATH:$HOME/.local/bin
          echo 'export PATH=$PATH:$HOME/.local/bin' >> ~/.bashrc
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py --user
          pip3 install awsebcli --upgrade --user

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -r ${{ secrets.AWS_REGION }} -p Node.js
          eb create ${{ secrets.ELASTIC_BEANSTALK_APP_NAME }} --single --env-name ${{ secrets.ELASTIC_BEANSTALK_ENV_NAME }}
          eb deploy
